# Site settings
title: Milena Zielonka
email: esy_floresy@op.pl
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zilenamielonka.pl/" # the base hostname & protocol for your site
ga: 
published: true


# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true

# Plugin
plugins:
- jekyll-autoprefixer
